In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D
import numpy as np
from tensorflow.keras.preprocessing import image

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [ ]:
training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/Cotton Disease/train',
                                                 target_size=  (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# Preprocessing the Test set
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/Cotton Disease/test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 1951 images belonging to 4 classes.
Found 106 images belonging to 4 classes.


In [ ]:
# Initialising the CNN
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32,padding="same",kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

# Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Adding a second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32,padding='same',kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

# Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=4, activation='softmax')) 

In [ ]:
cnn.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 8192)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1048704   
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 5

In [ ]:
# Compiling the CNN
cnn.compile(optimizer = 'adam',loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

Epoch 1/25
61/61 [==============================] - 315s 5s/step - loss: 1.1816 - accuracy: 0.4890 - val_loss: 1.1434 - val_accuracy: 0.5377
Epoch 2/25
61/61 [==============================] - 30s 484ms/step - loss: 0.9042 - accuracy: 0.6545 - val_loss: 0.8511 - val_accuracy: 0.6226
Epoch 3/25
61/61 [==============================] - 29s 483ms/step - loss: 0.7198 - accuracy: 0.7273 - val_loss: 0.6790 - val_accuracy: 0.7264
Epoch 4/25
61/61 [==============================] - 30s 486ms/step - loss: 0.6989 - accuracy: 0.7294 - val_loss: 0.7545 - val_accuracy: 0.6792
Epoch 5/25
61/61 [==============================] - 29s 482ms/step - loss: 0.6321 - accuracy: 0.7473 - val_loss: 0.8480 - val_accuracy: 0.6509
Epoch 6/25
61/61 [==============================] - 30s 486ms/step - loss: 0.5293 - accuracy: 0.7996 - val_loss: 0.8790 - val_accuracy: 0.6321
Epoch 7/25
61/61 [==============================] - 30s 485ms/step - loss: 0.5133 - accuracy: 0.8083 - val_loss: 0.7514 - val_accuracy: 0.6698
E

In [ ]:
test_image = image.load_img('/content/drive/MyDrive/Cotton Disease/test/diseased cotton plant/dd (29)_iaip.jpg',
                            target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

In [ ]:
result

array([[2.5659274e-06, 9.7487158e-01, 1.8270639e-07, 2.5125667e-02]],
      dtype=float32)

In [ ]:
result = result.ravel() 


In [ ]:
result

array([2.5659274e-06, 9.7487158e-01, 1.8270639e-07, 2.5125667e-02],
      dtype=float32)

In [ ]:
n = len(result)
def largest(arr,n):
  
    # Initialize maximum element
    max = arr[0]
  
    # Traverse array elements from second
    # and compare every element with 
    # current max
    for i in range(1, n):
        if arr[i] > max:
            max = arr[i]
    return max
ans=largest(result,n)
print ("Largest in given array is",ans)


Largest in given array is 0.9748716


In [ ]:
result.sort
result 

array([2.5659274e-06, 9.7487158e-01, 1.8270639e-07, 2.5125667e-02],
      dtype=float32)

In [ ]:
result=result.tolist() 

In [ ]:
import numpy as np
result1=["diseased_leaf","diseased_plant","fresh_leaf","fresh_plant"]


In [ ]:

index = np.argmax(result)
print(index)
 
print("Largest element present in given array: " +str(ans)+" And it belongs to " +str(result1[index]) +" class.");      


1
Largest element present in given array: 0.9748716 And it belongs to diseased_plant class.
